#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-netlib-java
Version  : 1.1.2
Release  : 3
URL      : https://github.com/fommil/netlib-java/archive/1.1.2.tar.gz
Source0  : https://github.com/fommil/netlib-java/archive/1.1.2.tar.gz
Source1  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/all/1.1.2/all-1.1.2.pom
Source2  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/core/1.1.2/core-1.1.2.jar
Source3  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/core/1.1.2/core-1.1.2.pom
Source4  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/core/1.1/core-1.1.pom
Source5  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/native_ref-java/1.1/native_ref-java-1.1.jar
Source6  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/native_ref-java/1.1/native_ref-java-1.1.pom
Source7  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/native_ref-xbuilds/1.1/native_ref-xbuilds-1.1.pom
Source8  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/native_ref/1.1/native_ref-1.1.pom
Source9  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/native_system-java/1.1/native_system-java-1.1.jar
Source10  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/native_system-java/1.1/native_system-java-1.1.pom
Source11  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/native_system-xbuilds/1.1/native_system-xbuilds-1.1.pom
Source12  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/native_system/1.1/native_system-1.1.pom
Source13  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/netlib-native_ref-linux-armhf/1.1/netlib-native_ref-linux-armhf-1.1-natives.jar
Source14  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/netlib-native_ref-linux-armhf/1.1/netlib-native_ref-linux-armhf-1.1.pom
Source15  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/netlib-native_ref-linux-i686/1.1/netlib-native_ref-linux-i686-1.1-natives.jar
Source16  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/netlib-native_ref-linux-i686/1.1/netlib-native_ref-linux-i686-1.1.pom
Source17  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/netlib-native_ref-linux-x86_64/1.1/netlib-native_ref-linux-x86_64-1.1-natives.jar
Source18  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/netlib-native_ref-linux-x86_64/1.1/netlib-native_ref-linux-x86_64-1.1.pom
Source19  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/netlib-native_ref-osx-x86_64/1.1/netlib-native_ref-osx-x86_64-1.1-natives.jar
Source20  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/netlib-native_ref-osx-x86_64/1.1/netlib-native_ref-osx-x86_64-1.1.pom
Source21  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/netlib-native_ref-win-i686/1.1/netlib-native_ref-win-i686-1.1-natives.jar
Source22  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/netlib-native_ref-win-i686/1.1/netlib-native_ref-win-i686-1.1.pom
Source23  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/netlib-native_ref-win-x86_64/1.1/netlib-native_ref-win-x86_64-1.1-natives.jar
Source24  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/netlib-native_ref-win-x86_64/1.1/netlib-native_ref-win-x86_64-1.1.pom
Source25  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/netlib-native_system-linux-armhf/1.1/netlib-native_system-linux-armhf-1.1-natives.jar
Source26  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/netlib-native_system-linux-armhf/1.1/netlib-native_system-linux-armhf-1.1.pom
Source27  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/netlib-native_system-linux-i686/1.1/netlib-native_system-linux-i686-1.1-natives.jar
Source28  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/netlib-native_system-linux-i686/1.1/netlib-native_system-linux-i686-1.1.pom
Source29  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/netlib-native_system-linux-x86_64/1.1/netlib-native_system-linux-x86_64-1.1-natives.jar
Source30  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/netlib-native_system-linux-x86_64/1.1/netlib-native_system-linux-x86_64-1.1.pom
Source31  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/netlib-native_system-osx-x86_64/1.1/netlib-native_system-osx-x86_64-1.1-natives.jar
Source32  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/netlib-native_system-osx-x86_64/1.1/netlib-native_system-osx-x86_64-1.1.pom
Source33  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/netlib-native_system-win-i686/1.1/netlib-native_system-win-i686-1.1-natives.jar
Source34  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/netlib-native_system-win-i686/1.1/netlib-native_system-win-i686-1.1.pom
Source35  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/netlib-native_system-win-x86_64/1.1/netlib-native_system-win-x86_64-1.1-natives.jar
Source36  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/netlib-native_system-win-x86_64/1.1/netlib-native_system-win-x86_64-1.1.pom
Source37  : https://repo.maven.apache.org/maven2/com/github/fommil/netlib/parent/1.1/parent-1.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-3.0
Requires: mvn-netlib-java-data = %{version}-%{release}

%description
This folder contains the netlib reference implementations.
The netlib API is a Fortran API. The recommended C interface is via
the CBLAS wrapper (for BLAS) and the LAPACKE wrapper (for LAPACK).

%package data
Summary: data components for the mvn-netlib-java package.
Group: Data

%description data
data components for the mvn-netlib-java package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/all/1.1.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/all/1.1.2/all-1.1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/core/1.1.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/core/1.1.2/core-1.1.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/core/1.1.2
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/core/1.1.2/core-1.1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/core/1.1
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/core/1.1/core-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/native_ref-java/1.1
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/native_ref-java/1.1/native_ref-java-1.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/native_ref-java/1.1
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/native_ref-java/1.1/native_ref-java-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/native_ref-xbuilds/1.1
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/native_ref-xbuilds/1.1/native_ref-xbuilds-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/native_ref/1.1
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/native_ref/1.1/native_ref-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/native_system-java/1.1
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/native_system-java/1.1/native_system-java-1.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/native_system-java/1.1
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/native_system-java/1.1/native_system-java-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/native_system-xbuilds/1.1
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/native_system-xbuilds/1.1/native_system-xbuilds-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/native_system/1.1
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/native_system/1.1/native_system-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-linux-armhf/1.1
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-linux-armhf/1.1/netlib-native_ref-linux-armhf-1.1-natives.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-linux-armhf/1.1
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-linux-armhf/1.1/netlib-native_ref-linux-armhf-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-linux-i686/1.1
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-linux-i686/1.1/netlib-native_ref-linux-i686-1.1-natives.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-linux-i686/1.1
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-linux-i686/1.1/netlib-native_ref-linux-i686-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-linux-x86_64/1.1
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-linux-x86_64/1.1/netlib-native_ref-linux-x86_64-1.1-natives.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-linux-x86_64/1.1
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-linux-x86_64/1.1/netlib-native_ref-linux-x86_64-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-osx-x86_64/1.1
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-osx-x86_64/1.1/netlib-native_ref-osx-x86_64-1.1-natives.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-osx-x86_64/1.1
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-osx-x86_64/1.1/netlib-native_ref-osx-x86_64-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-win-i686/1.1
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-win-i686/1.1/netlib-native_ref-win-i686-1.1-natives.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-win-i686/1.1
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-win-i686/1.1/netlib-native_ref-win-i686-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-win-x86_64/1.1
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-win-x86_64/1.1/netlib-native_ref-win-x86_64-1.1-natives.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-win-x86_64/1.1
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-win-x86_64/1.1/netlib-native_ref-win-x86_64-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-linux-armhf/1.1
cp %{SOURCE25} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-linux-armhf/1.1/netlib-native_system-linux-armhf-1.1-natives.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-linux-armhf/1.1
cp %{SOURCE26} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-linux-armhf/1.1/netlib-native_system-linux-armhf-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-linux-i686/1.1
cp %{SOURCE27} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-linux-i686/1.1/netlib-native_system-linux-i686-1.1-natives.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-linux-i686/1.1
cp %{SOURCE28} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-linux-i686/1.1/netlib-native_system-linux-i686-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-linux-x86_64/1.1
cp %{SOURCE29} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-linux-x86_64/1.1/netlib-native_system-linux-x86_64-1.1-natives.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-linux-x86_64/1.1
cp %{SOURCE30} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-linux-x86_64/1.1/netlib-native_system-linux-x86_64-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-osx-x86_64/1.1
cp %{SOURCE31} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-osx-x86_64/1.1/netlib-native_system-osx-x86_64-1.1-natives.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-osx-x86_64/1.1
cp %{SOURCE32} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-osx-x86_64/1.1/netlib-native_system-osx-x86_64-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-win-i686/1.1
cp %{SOURCE33} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-win-i686/1.1/netlib-native_system-win-i686-1.1-natives.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-win-i686/1.1
cp %{SOURCE34} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-win-i686/1.1/netlib-native_system-win-i686-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-win-x86_64/1.1
cp %{SOURCE35} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-win-x86_64/1.1/netlib-native_system-win-x86_64-1.1-natives.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-win-x86_64/1.1
cp %{SOURCE36} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-win-x86_64/1.1/netlib-native_system-win-x86_64-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/parent/1.1
cp %{SOURCE37} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/parent/1.1/parent-1.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/github/fommil/netlib/all/1.1.2/all-1.1.2.pom
/usr/share/java/.m2/repository/com/github/fommil/netlib/core/1.1.2/core-1.1.2.jar
/usr/share/java/.m2/repository/com/github/fommil/netlib/core/1.1.2/core-1.1.2.pom
/usr/share/java/.m2/repository/com/github/fommil/netlib/core/1.1/core-1.1.pom
/usr/share/java/.m2/repository/com/github/fommil/netlib/native_ref-java/1.1/native_ref-java-1.1.jar
/usr/share/java/.m2/repository/com/github/fommil/netlib/native_ref-java/1.1/native_ref-java-1.1.pom
/usr/share/java/.m2/repository/com/github/fommil/netlib/native_ref-xbuilds/1.1/native_ref-xbuilds-1.1.pom
/usr/share/java/.m2/repository/com/github/fommil/netlib/native_ref/1.1/native_ref-1.1.pom
/usr/share/java/.m2/repository/com/github/fommil/netlib/native_system-java/1.1/native_system-java-1.1.jar
/usr/share/java/.m2/repository/com/github/fommil/netlib/native_system-java/1.1/native_system-java-1.1.pom
/usr/share/java/.m2/repository/com/github/fommil/netlib/native_system-xbuilds/1.1/native_system-xbuilds-1.1.pom
/usr/share/java/.m2/repository/com/github/fommil/netlib/native_system/1.1/native_system-1.1.pom
/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-linux-armhf/1.1/netlib-native_ref-linux-armhf-1.1-natives.jar
/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-linux-armhf/1.1/netlib-native_ref-linux-armhf-1.1.pom
/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-linux-i686/1.1/netlib-native_ref-linux-i686-1.1-natives.jar
/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-linux-i686/1.1/netlib-native_ref-linux-i686-1.1.pom
/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-linux-x86_64/1.1/netlib-native_ref-linux-x86_64-1.1-natives.jar
/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-linux-x86_64/1.1/netlib-native_ref-linux-x86_64-1.1.pom
/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-osx-x86_64/1.1/netlib-native_ref-osx-x86_64-1.1-natives.jar
/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-osx-x86_64/1.1/netlib-native_ref-osx-x86_64-1.1.pom
/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-win-i686/1.1/netlib-native_ref-win-i686-1.1-natives.jar
/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-win-i686/1.1/netlib-native_ref-win-i686-1.1.pom
/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-win-x86_64/1.1/netlib-native_ref-win-x86_64-1.1-natives.jar
/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_ref-win-x86_64/1.1/netlib-native_ref-win-x86_64-1.1.pom
/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-linux-armhf/1.1/netlib-native_system-linux-armhf-1.1-natives.jar
/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-linux-armhf/1.1/netlib-native_system-linux-armhf-1.1.pom
/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-linux-i686/1.1/netlib-native_system-linux-i686-1.1-natives.jar
/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-linux-i686/1.1/netlib-native_system-linux-i686-1.1.pom
/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-linux-x86_64/1.1/netlib-native_system-linux-x86_64-1.1-natives.jar
/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-linux-x86_64/1.1/netlib-native_system-linux-x86_64-1.1.pom
/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-osx-x86_64/1.1/netlib-native_system-osx-x86_64-1.1-natives.jar
/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-osx-x86_64/1.1/netlib-native_system-osx-x86_64-1.1.pom
/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-win-i686/1.1/netlib-native_system-win-i686-1.1-natives.jar
/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-win-i686/1.1/netlib-native_system-win-i686-1.1.pom
/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-win-x86_64/1.1/netlib-native_system-win-x86_64-1.1-natives.jar
/usr/share/java/.m2/repository/com/github/fommil/netlib/netlib-native_system-win-x86_64/1.1/netlib-native_system-win-x86_64-1.1.pom
/usr/share/java/.m2/repository/com/github/fommil/netlib/parent/1.1/parent-1.1.pom
