#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-netlib-java
Version  : 1.1.2
Release  : 1
URL      : https://github.com/fommil/netlib-java/archive/1.1.2.tar.gz
Source0  : https://github.com/fommil/netlib-java/archive/1.1.2.tar.gz
Source1  : https://repo1.maven.org/maven2/com/github/fommil/netlib/core/1.1.2/core-1.1.2.jar
Source2  : https://repo1.maven.org/maven2/com/github/fommil/netlib/core/1.1.2/core-1.1.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-3.0
Requires: mvn-netlib-java-data = %{version}-%{release}

%description
This folder contains the netlib reference implementations.
The netlib API is a Fortran API. The recommended C interface is via
the CBLAS wrapper (for BLAS) and the LAPACKE wrapper (for LAPACK).

%package data
Summary: data components for the mvn-netlib-java package.
Group: Data

%description data
data components for the mvn-netlib-java package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/core/1.1.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/core/1.1.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/core/1.1.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/netlib/core/1.1.2


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/github/fommil/netlib/core/1.1.2/core-1.1.2.jar
/usr/share/java/.m2/repository/com/github/fommil/netlib/core/1.1.2/core-1.1.2.pom
